name: 'Trigger workflow action'
description: 'Trigger workflow in another repository'
inputs:
  token:
    description: 'personal access token'
    required: true
  repository:
    description: 'repository'
    required: true
  branch:
    description: 'branch'
    required: true
    default: 'main'
runs:
  using: 'composite'
  steps:
    - id: get-workflows
      shell: bash
      run: echo "::set-output name=workflows::$(curl -H 'Authorization: Bearer ${{ inputs.token }}' -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/${{ inputs.repository }}/actions/workflows)"

    - shell: bash
      run: |
        workflowId=${{ fromJson(steps.get-workflows.outputs.workflows).workflows[0].id }}

        if [[ -z "$workflowId" ]]; then
          curl --header 'Authorization: Bearer ${{ inputs.token }}' -X POST https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${workflowId}/dispatches -d '{"ref":"${{ inputs.branch }}"}'
        fi