name: 'Trigger workflow action'
description: 'Trigger workflow in another repository'
inputs:
  token:
    description: 'personal access token'
    required: true
  repository:
    description: 'repository'
    required: true
  workflowId:
    description: 'ID of workflow'
    required: true
  branch:
    description: 'branch'
    required: true
    default: 'main'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: curl --header 'Authorization: Bearer ${{ inputs.token }}' -X POST https://api.github.com/repos/${{ inputs.repository }}/actions/workflows/${{ inputs.workflowId }}/dispatches -d '{"ref":"${{ inputs.branch }}"}'